const form = () => ({
  recipe: {
    name: '',
    difficulty: 'easy',
    servings: 1,
    duration: 0,
  },
  forms: {
    $form: {
      initialValue: {
        recipe: {
          name: '',
          difficulty: 'easy',
          servings: 1,
          duration: 0,
        },
      },
      focus: false,
      pending: false,
      pristine: true,
      submitted: false,
      submitFailed: false,
      retouched: false,
      touched: false,
      valid: true,
      validating: false,
      validated: false,
      validity: {},
      errors: {},
      intents: [],
      model: 'form',
      value: {
        recipe: {
          name: '',
          difficulty: 'easy',
          servings: 1,
          duration: 0,
        },
      },
    },
    recipe: {
      $form: {
        initialValue: {
          name: '',
          difficulty: 'easy',
          servings: 1,
          duration: 0,
        },
        focus: false,
        pending: false,
        pristine: true,
        submitted: false,
        submitFailed: false,
        retouched: false,
        touched: false,
        valid: true,
        validating: false,
        validated: false,
        validity: {},
        errors: {},
        intents: [],
        model: 'form.recipe',
        value: {
          name: '',
          difficulty: 'easy',
          servings: 1,
          duration: 0,
        },
      },
      name: {
        initialValue: '',
        focus: false,
        pending: false,
        pristine: true,
        submitted: false,
        submitFailed: false,
        retouched: false,
        touched: false,
        valid: true,
        validating: false,
        validated: false,
        validity: {},
        errors: {},
        intents: [],
        model: 'form.recipe.name',
        value: '',
      },
      difficulty: {
        initialValue: 'easy',
        focus: false,
        pending: false,
        pristine: true,
        submitted: false,
        submitFailed: false,
        retouched: false,
        touched: false,
        valid: true,
        validating: false,
        validated: false,
        validity: {},
        errors: {},
        intents: [],
        model: 'form.recipe.difficulty',
        value: 'easy',
      },
      servings: {
        initialValue: 1,
        focus: false,
        pending: false,
        pristine: true,
        submitted: false,
        submitFailed: false,
        retouched: false,
        touched: false,
        valid: true,
        validating: false,
        validated: false,
        validity: {},
        errors: {},
        intents: [],
        model: 'form.recipe.servings',
        value: 1,
      },
      duration: {
        initialValue: 0,
        focus: false,
        pending: false,
        pristine: true,
        submitted: false,
        submitFailed: false,
        retouched: false,
        touched: false,
        valid: true,
        validating: false,
        validated: false,
        validity: {},
        errors: {},
        intents: [],
        model: 'form.recipe.duration',
        value: 0,
      },
    },
  },
})

export default form
